name: Publish Docker image

on: [ push ]

    

jobs:
  login:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
      run: |
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: change 
      run: |
        cd /home/pier/weather-app
    - name: build
      run: |  
        docker build -f Dockerfile
   


    