name: Publish Docker image

on: push
  
jobs:
  build-container:
    name: Push Docker image to Docker Hub( build docker container image )
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }}
    

