name: Publish Docker image

on:
  push:
    branches: master

jobs:

  login:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
          uses: docker/login-action@v1
      
          run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    