name: Publish Docker image

on: push
  
jobs:
  build-container:
    name: Push Docker image to Docker Hub( build docker container image )
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
    
      - name: Log in to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pier46/weather-app
          tags: latest, ${{ github.run_number }}
