name: Publish Docker image

on: push

env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: samples
  
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      -name: checkout repository
       uses: actions/checkout@v2

      -name: login
       uses: docker/login-in.action@v1
       with:
         registry: ${{ env.REGISTRY }}
         username: ${{github.actor}}
         password: ${{secrets.GITHUB_TOKEN}}


      

