name: Publish Docker image

on:
  push:
    branches: master

jobs:

  login:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      - name: Check out code
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} --password-stdin
    