name: Publish Docker image

on: push
  
jobs:
  build-container:
    name: Push Docker image to Docker Hub( build docker container image )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out code
        run: echo ${{ secrets.DOCKER_PASSWORD }} | winpty docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    

